server:
  #  端口
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接个数
      minimum-idle: 5
      # 空闲连接最大存活时间
      idle-timeout: 180000
      # 最大连接数
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 最大存活时间
      max-lifetime: 1800000
      # 连接超时时间
      connection-timeout: 30000
      # 连接测试语句
      connection-test-query: SELECT 1
  redis:
    host: localhost
    port: 6379
    # 超时时间
    timeout: 10000ms
    database: 0
    lettuce:
      pool:
        # 最大连接处
        max-active: 1024
        # 空闲连接数
        max-idle: 200
        # 最大连接阻塞等待时间
        max-wait: 10000ms
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    username: ruby
    password: ruby
    virtual-host: /ruby
    host: 106.14.25.82
    port: 5672
    # 开启消息确认回调
    publisher-confirm-type: correlated
    # 开启消息失败回调
    publisher-returns: true

mybatis-plus:
  # 配置文件地址
  mapper-locations: classpath*:/mapper/*.xml
  # 驼峰命名
  type-aliases-package: com.road.pojo
  configuration:
    map-underscore-to-camel-case: false # 不使用自动驼峰命名

#MyBatis SQL语句打印
logging:
  level:
    com.road.mapper: debug

# JWT配置

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加解密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间
  expiration: 604800
  # JWT负载中拿到开头
  tokenHead: Bearer








